version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 3000
      runas: root
    - location: scripts/start_server
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 3000
      runas: root
