#!/bin/bash
docker login -u wadieabuissa -p qivvac-1Hybdu-towrax
docker stop wad-final
docker rm wad-final
docker pull wadieabuissa/finalpyhub:30
sudo docker run --name wad-final -it -d -p 5000:5000 wadieabuissa/finalpyhub:30
